// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1728738150);
user_pref("browser.search.region", "RU");
user_pref("calendar.caldav.googleResync", 1728738148);
user_pref("calendar.list.sortOrder", "1da6e8b6-d03d-4c39-8ab5-5ace6b09c48c");
user_pref("calendar.registry.1da6e8b6-d03d-4c39-8ab5-5ace6b09c48c.calendar-main-default", true);
user_pref("calendar.registry.1da6e8b6-d03d-4c39-8ab5-5ace6b09c48c.calendar-main-in-composite", true);
user_pref("calendar.registry.1da6e8b6-d03d-4c39-8ab5-5ace6b09c48c.disabled", true);
user_pref("calendar.registry.1da6e8b6-d03d-4c39-8ab5-5ace6b09c48c.name", "Мой календарь");
user_pref("calendar.registry.1da6e8b6-d03d-4c39-8ab5-5ace6b09c48c.type", "storage");
user_pref("calendar.registry.1da6e8b6-d03d-4c39-8ab5-5ace6b09c48c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Moscow");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1728738147);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240903191356");
user_pref("extensions.lastAppVersion", "115.15.0");
user_pref("extensions.lastPlatformVersion", "115.15.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"d9fc68d9-d4a9-494c-84bf-197106b551e3\",\"google@search.mozilla.org\":\"dc190fa1-d555-48cf-9bf6-3d8189d28193\",\"ddg@search.mozilla.org\":\"cd457cc6-24c7-466b-8d99-aea8cf947322\",\"priceru@search.mozilla.org\":\"d28e3fd5-5096-4dce-8234-db276b4e961d\",\"wikipedia@search.mozilla.org\":\"924e63cc-d3e8-478d-95dd-90d41ed994f0\",\"ozonru@search.mozilla.org\":\"580316f5-db7d-4a35-8c7a-3e394b6dd19a\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "a36074fc-c45b-408a-90fd-52096bfebf6");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.15.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важное");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Рабочее");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Личное");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "К исполнению");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Отложено");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1728738140);
user_pref("toolkit.telemetry.cachedClientID", "2da0dda1-a99f-4b62-9abb-3ec2e0db285b");
user_pref("toolkit.telemetry.previousBuildID", "20240903191356");
